upstream battleflow_app {
    server battleflow:5001;
}

log_format battleflow '$remote_addr - $host - "$http_host" - "$http_x_forwarded_host" '
                      '"$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';

server {
    listen 80 default_server;
    server_name _;

    access_log /var/log/nginx/access.log battleflow;

    client_max_body_size 100m;

    location / {
        proxy_pass http://battleflow_app;
        proxy_http_version 1.1;

        proxy_set_header Host battleflow.atrust.sangfor.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host battleflow.atrust.sangfor.com;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_buffering off;
    }
}
