import { NextRequest, NextResponse } from 'next/server';
import type { QueryResultRow } from 'pg';
import { requireOrganizationContext, requirePermission } from '@/lib/auth/server';
import { AuthError } from '@/lib/auth/types';
import { requireWorkflowAccess } from '@/lib/resource-metadata-repository';
import { getWorkflow } from '@/lib/workflow-registry';
import { queryPostgres } from '@/storage/database/postgres-client';

export const runtime = 'nodejs';

interface PrdDocumentRow extends QueryResultRow {
  id: string;
  workflow_id: string;
  organization_id: string;
  title: string;
  content: string;
  version: string;
  created_by: string | null;
  created_at: Date | string;
  updated_at: Date | string | null;
}

function toIso(value: Date | string | null): string | null {
  if (!value) return null;
  return value instanceof Date ? value.toISOString() : value;
}

function mapPrdDocument(row: PrdDocumentRow) {
  return {
    id: row.id,
    workflow_id: row.workflow_id,
    organization_id: row.organization_id,
    title: row.title,
    content: row.content,
    version: row.version,
    created_by: row.created_by,
    created_at: toIso(row.created_at),
    updated_at: toIso(row.updated_at),
  };
}

function jsonError(error: unknown, fallback: string) {
  if (error instanceof AuthError) {
    return NextResponse.json({ error: error.message }, { status: error.status });
  }

  console.error('PRD route error:', error);
  return NextResponse.json({ error: fallback }, { status: 500 });
}

// GET /api/prd?workflow_id=xxx - Get PRD for a workflow
export async function GET(request: NextRequest) {
  try {
    const context = await requireOrganizationContext(request);
    const { searchParams } = new URL(request.url);
    const workflowId = searchParams.get('workflow_id');

    if (!workflowId) {
      return NextResponse.json({ error: 'Workflow ID is required' }, { status: 400 });
    }

    await requireWorkflowAccess(context, workflowId, 'workflow.read');

    const result = await queryPostgres<PrdDocumentRow>(
      `
        SELECT id, workflow_id, organization_id, title, content, version, created_by, created_at, updated_at
        FROM prd_documents
        WHERE workflow_id = $1
          AND organization_id = $2
        ORDER BY created_at DESC
      `,
      [workflowId, context.activeOrganization.id],
    );

    return NextResponse.json({ documents: result.rows.map(mapPrdDocument) }, {
      headers: { 'Cache-Control': 'no-store' },
    });
  } catch (error) {
    return jsonError(error, 'Failed to fetch PRD documents');
  }
}

// POST /api/prd - Generate PRD from workflow
export async function POST(request: NextRequest) {
  try {
    const context = await requireOrganizationContext(request);
    const body = await request.json() as Record<string, unknown>;
    const workflowId = typeof body.workflow_id === 'string' ? body.workflow_id.trim() : '';
    const requestedTitle = typeof body.title === 'string' ? body.title.trim() : '';

    if (!workflowId) {
      return NextResponse.json({ error: 'Workflow ID is required' }, { status: 400 });
    }

    await requireWorkflowAccess(context, workflowId, 'workflow.read');
    requirePermission(context, 'prd_document.create', {
      organizationId: context.activeOrganization.id,
      resourceType: 'prd_document',
      resourceId: workflowId,
      ownerUserId: context.user.id,
    });

    const workflow = await getWorkflow(workflowId);
    if (!workflow) {
      return NextResponse.json({ error: 'Workflow not found' }, { status: 404 });
    }

    const completedSteps = workflow.steps.filter((step) => step.status === 'completed' && step.output);
    if (completedSteps.length === 0) {
      return NextResponse.json({ error: 'No completed steps with output to generate PRD from' }, { status: 400 });
    }

    const title = requestedTitle || workflow.name;
    const generatedDate = new Date().toISOString().slice(0, 10);
    const prdContent = [
      `# ${title}`,
      '',
      `> Generated by BattleFlow on ${generatedDate}`,
      '',
      '---',
      '',
      ...completedSteps.flatMap((step) => [
        `## ${step.name}`,
        '',
        step.output || '',
        '',
        '---',
        '',
      ]),
    ].join('\n');

    const result = await queryPostgres<PrdDocumentRow>(
      `
        INSERT INTO prd_documents (workflow_id, organization_id, title, content, version, created_by, created_at, updated_at)
        VALUES ($1, $2, $3, $4, '1.0.0', $5, now(), now())
        RETURNING id, workflow_id, organization_id, title, content, version, created_by, created_at, updated_at
      `,
      [workflowId, context.activeOrganization.id, title, prdContent, context.user.id],
    );

    return NextResponse.json({ document: mapPrdDocument(result.rows[0]) }, {
      headers: { 'Cache-Control': 'no-store' },
    });
  } catch (error) {
    return jsonError(error, 'Failed to generate PRD');
  }
}
