import { NextRequest, NextResponse } from 'next/server';
import { getSupabaseClient } from '@/storage/database/supabase-client';

// GET /api/prd?workflow_id=xxx - Get PRD for a workflow
export async function GET(request: NextRequest) {
  try {
    const token = request.headers.get('x-session') || undefined;
    const client = getSupabaseClient(token);
    const { searchParams } = new URL(request.url);
    const workflowId = searchParams.get('workflow_id');

    if (!workflowId) {
      return NextResponse.json({ error: 'Workflow ID is required' }, { status: 400 });
    }

    const { data, error } = await client
      .from('prd_documents')
      .select('*')
      .eq('workflow_id', workflowId)
      .order('created_at', { ascending: false });

    if (error) throw new Error(`Failed to fetch PRD: ${error.message}`);

    return NextResponse.json({ documents: data });
  } catch (error) {
    console.error('PRD GET error:', error);
    return NextResponse.json({ error: 'Failed to fetch PRD documents' }, { status: 500 });
  }
}

// POST /api/prd - Generate PRD from workflow
export async function POST(request: NextRequest) {
  try {
    const token = request.headers.get('x-session') || undefined;
    const client = getSupabaseClient(token);
    const body = await request.json();
    const { workflow_id, title } = body;

    if (!workflow_id) {
      return NextResponse.json({ error: 'Workflow ID is required' }, { status: 400 });
    }

    // Get workflow
    const { data: workflow, error: wfError } = await client
      .from('workflows')
      .select('*')
      .eq('id', workflow_id)
      .maybeSingle();

    if (wfError) throw new Error(`Failed to fetch workflow: ${wfError.message}`);
    if (!workflow) return NextResponse.json({ error: 'Workflow not found' }, { status: 404 });

    // Get all steps with their outputs
    const { data: steps, error: stepsError } = await client
      .from('workflow_steps')
      .select('*')
      .eq('workflow_id', workflow_id)
      .order('step_index', { ascending: true });

    if (stepsError) throw new Error(`Failed to fetch steps: ${stepsError.message}`);

    // Compile PRD content from all step outputs
    const completedSteps = (steps || []).filter((s: { status: string; output: string | null }) => s.status === 'completed' && s.output);

    if (completedSteps.length === 0) {
      return NextResponse.json({ error: 'No completed steps with output to generate PRD from' }, { status: 400 });
    }

    let prdContent = `# ${title || workflow.name}\n\n`;
    prdContent += `> Generated by BattleFlow on ${new Date().toLocaleDateString()}\n\n`;
    prdContent += `---\n\n`;

    for (const step of completedSteps) {
      prdContent += `## ${step.name}\n\n`;
      prdContent += `${step.output}\n\n`;
      prdContent += `---\n\n`;
    }

    // Save PRD document
    const { data: prd, error: prdError } = await client
      .from('prd_documents')
      .insert({
        workflow_id,
        organization_id: workflow.organization_id,
        title: title || workflow.name,
        content: prdContent,
        version: '1.0.0',
        created_by: 'current_user',
      })
      .select()
      .single();

    if (prdError) throw new Error(`Failed to save PRD: ${prdError.message}`);

    return NextResponse.json({ document: prd });
  } catch (error) {
    console.error('PRD POST error:', error);
    return NextResponse.json({ error: 'Failed to generate PRD' }, { status: 500 });
  }
}
